openapi: "3.0.2"
info:
  title: API Of Laundry
  version: "1.0"
servers:
  - url: http://127.0.0.1:8080/api/v1
security:
  - bearerAuth: []
paths:
  /security/login:
    post:
      description: ""
      tags:
        - Security
      security:
        - basicAuth: []
      responses:
        "200":
          description: "Ok"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success
                  data:
                    type: object
                    properties:
                      user_id:
                        type: integer
                        example: 123
                      token:
                        type: string
                        example: this-is-token
                      refresh_token:
                        type: string
                        example: this-is-token
        "404":
          $ref: "#/components/responses/responseErrorNotFound"
        "500":
          $ref: "#/components/responses/responseErrorSystem"
  /security/refresh:
    post:
      description: ""
      tags:
        - Security
      responses:
        "200":
          description: "Ok"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: this-is-token
                      refresh_token:
                        type: string
                        example: this-is-token
        "404":
          $ref: "#/components/responses/responseErrorNotFound"
        "500":
          $ref: "#/components/responses/responseErrorSystem"
  /security/services:
    get:
      description: ''
      deprecated: false
      tags:
        - Security
      parameters: []
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success
                  data:
                    type: array
                    items:
                      anyOf:
                        - type: object
                          properties:
                            service_id:
                              type: integer
                              example: 1
                            service_name:
                              type: string
                              example: Security
        "400":
          $ref: "#/components/responses/responseErrorBadRequest"
        "401":
          $ref: "#/components/responses/responseErrorUnauthorized"
        "500":
          $ref: "#/components/responses/responseErrorSystem"
  /security/accesses/user/:user_type:
    get:
      description: ""
      tags:
        - Security
      parameters:
        - in: path
          name: user_type
          description: Get access based on user type
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success
                  data:
                    type: object
                    properties:
                      api_id:
                        type: array
                        items:
                          anyOf:
                            - type: integer
                              example: 1
                            - type: integer
                              example: 2
                            - type: integer
                              example: 3
        "400":
          $ref: "#/components/responses/responseErrorBadRequest"
        "401":
          $ref: "#/components/responses/responseErrorUnauthorized"
        "404":
          $ref: "#/components/responses/responseErrorNotFound"
        "500":
          $ref: "#/components/responses/responseErrorSystem"
    patch:
      description: ""
      tags:
        - Security
      parameters:
        - in: path
          name: user_type
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                api_id:
                  type: array
                  items:
                    anyOf:
                      - type: integer
                        example: 1
                      - type: integer
                        example: 2
                      - type: integer
                        example: 3
              required:
                - api_id
      responses:
        "200":
          $ref: "#/components/responses/responseSuccessOk"
        "400":
          $ref: "#/components/responses/responseErrorBadRequest"
        "401":
          $ref: "#/components/responses/responseErrorUnauthorized"
        "404":
          $ref: "#/components/responses/responseErrorNotFound"
        "500":
          $ref: "#/components/responses/responseErrorSystem"
  /security/services/:service_id/api:
    get:
      description: ''
      deprecated: false
      tags:
        - Security
      parameters:
        - in: path
          name: service_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success
                  data:
                    type: array
                    items:
                      anyOf:
                        - type: object
                          properties:
                            api_id:
                              type: integer
                              example: 1
                            api_name:
                              type: string
                              example: Login
                            method:
                              type: string
                              example: POST
                            endpoint:
                              type: string
                              example: /api/v1/security/login
        "400":
          $ref: "#/components/responses/responseErrorBadRequest"
        "401":
          $ref: "#/components/responses/responseErrorUnauthorized"
        "404":
          $ref: "#/components/responses/responseErrorNotFound"
        "500":
          $ref: "#/components/responses/responseErrorSystem"
  /security/version/support:
    post:
      description: ''
      tags:
        - Security
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                version:
                  type: string
                  example: v1.0.0
              required:
                - version
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success
                  data:
                    type: object
                    properties:
                      version:
                        type: string
                        example: v1.0.0
                      support:
                        type: boolean
                        example: true
        "404":
          $ref: "#/components/responses/responseErrorNotFound"
        "500":
          $ref: "#/components/responses/responseErrorSystem"
  /security/users/:user_id/password:
    put:
      description: ''
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
            example: 123
          required: true
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: myPassword
              required:
                - password
      tags:
        - Security
      responses:
        "200":
          $ref: "#/components/responses/responseSuccessOk"
        "400":
          $ref: "#/components/responses/responseErrorBadRequest"
        "401":
          $ref: "#/components/responses/responseErrorUnauthorized"
        "404":
          $ref: "#/components/responses/responseErrorNotFound"
        "500":
          $ref: "#/components/responses/responseErrorSystem"
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
    apiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  responses:
    responseSuccessOk:
        description: "Ok"
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: integer
                  example: 200
                message:
                  type: string
                  example: Success
                data:
                  type: object
                  example: null
    responseSuccessCreated:
      description: "Created"
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 201
              message:
                type: string
                example: Success
              data:
                type: object
                example: null
    responseErrorNotFound:
      description: "Data not found"
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 404
              message:
                type: string
                example: Data not found
              data:
                type: object
                example: null
    responseErrorConflict:
      description: "Data conflict"
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 409
              message:
                type: string
                example: Data conflict
              data:
                type: object
                example: null
    responseErrorBadRequest:
      description: "Bad request"
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 400
              message:
                type: string
                example: Please put correct value
              data:
                type: object
                example: null
    responseErrorUnauthorized:
      description: "Unauthorized access"
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 401
              message:
                type: string
                example: Unauthorized
              data:
                type: object
                example: null
    responseErrorUnprocessable:
      description: "Unprocessable entity"
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 422
              message:
                type: string
                example: Unprocessable entity
              data:
                type: object
                example: null
    responseErrorSystem:
      description: "Unexpected error"
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 500
              message:
                type: string
                example: Something when wrong
              data:
                type: object
                example: null
