version: "3.3"
services:
  db-security:
    container_name: db-laundry-security
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: security
    volumes:
      - mysql-laundry-security:/var/lib/mysql
    networks:
      - server-side
  
  db-users:
    container_name: db-laundry-users
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
    volumes:
      - mysql-laundry-users:/var/lib/mysql
    networks:
      - server-side

  # laundry:
  #   container_name: laundry-service
  #   image: laundry:latest
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   environment:
  #     DB_ADDRESS: db
  #     DB_USER: root
  #     DB_PASSWORD: root
  #     PATH_CONF: ../config
  #     FILE_CONF: local.conf
  #   depends_on:
  #     - db
  #     - adminer
  #     - redis
  #   networks:
  #     - server-side

  redis:
    container_name: redis-laundry
    image: redis:6.2.4
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-laundry:/data
    networks:
      - server-side

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - ./docs/openapi:/openapi
    ports:
      - 5050:8080
    environment:
      SWAGGER_JSON: /openapi/swagger.yaml

networks:
  server-side:

volumes:
  mysql-laundry-security:
  mysql-laundry-users:
  redis-laundry: